AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: up-notifier
Resources:
  WebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: webhook.lambda_handler
      Runtime: python3.9
      CodeUri: s3://general-lambda-artifacts/2886d2024710dc3109a38666bff0b070
      MemorySize: 128
      Timeout: 30
      Events:
        WebhookApiEvent:
          Type: Api
          Properties:
            Path: /webhook
            Method: post
    Metadata:
      SamResourceId: WebhookFunction
